import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "ecom-challenge",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
        <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 items-center px-4 md:px-6">
            <div className="flex w-full items-center justify-between">
              <Link className="mr-6 flex items-center space-x-2" href="/">
                <span className="font-bold">ACME Store</span>
              </Link>
              <nav className="flex items-center space-x-2 text-xs font-medium sm:space-x-4 sm:text-sm">
                <Link href="/category/1">Shirts</Link>
                <Link href="/category/2">Hoodies</Link>
                <Link href="/category/3">Summer</Link>
                <Link href="/category/4">Winter</Link>
              </nav>
            </div>
          </div>
        </header>
        {children}
        <footer className="border-t">
          <div className="container flex w-full shrink-0 flex-col items-center gap-2 px-4 py-6 sm:flex-row md:px-6">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              © 2024 ACME Store. All rights reserved.
            </p>
            <nav className="flex gap-4 sm:ml-auto sm:gap-6">
              <Link className="text-xs underline-offset-4 hover:underline" href="#">
                Terms of Service
              </Link>
              <Link className="text-xs underline-offset-4 hover:underline" href="#">
                Privacy
              </Link>
            </nav>
          </div>
        </footer>
      </body>
    </html>
  );
}
